### ISSUE TITLE
Building HybriDroid

### ISSUE THREAD

**Issue by arvindksilvan** [SunghoLee/HybriDroid#3]
Hello! I've been trying to locate the build script based on the issue from here: #2 
However I've unable to find any build script. Any idea how I can go about building HybriDroid? I would greatly appreciate your reply. Thank you.

**Comment by SunghoLee** [comment]
Hi! Thank you for your interest. The build.xml file is a build script for HybriDroid. You can build HybriDroid using ant and the script. The build script is extracted from IntelliJ, so you should install IntelliJ before building HybriDroid.
