### ISSUE TITLE
run HybriDroid

### ISSUE THREAD

**Issue by jennifersuggar** [SunghoLee/HybriDroid#4]
here is my  wala.properties file configuration
// Java runtime directory
java_runtime_dir=/home/czf/java/jdk1.8.0_112/jre/lib
// Android rt directory
android_rt_jar=/home/czf/HybriDroid-master/data/android.jar
---------------------------------------------------------------------------------
when I run HybriDroid，I encounter this problem below：
`root@czf:/home/czf/HybriDroid-master# java -jar hybridroid.jar -cfg -t apps/NormalAliasFlowTest.apk -p wala.properties
#lib: /home/czf/HybriDroid-master/data/android.jar(true)
I: Using Apktool 2.0.2 on NormalAliasFlowTest.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
===== App Data =====

  version: 2.0.2
  apkFileName: NormalAliasFlowTest.apk
  isFrameworkApk: false
  usesFramework: 
    ids: -1
  sdkInfo: 
    minSdkVersion: '8'
    targetSdkVersion: '21'
  packageInfo: 
    forced-package-id: '127'
  versionInfo: 
    versionCode: '1'
    versionName: '1.0'
  sharedLibrary: false
  doNotCompress: -resources.arsc
====================
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Field Def analysis...
Build Constraint Graph...
Optimize Constraint Graph...
Solving the constraints...
#StringAnalysisEndTime: 31001
It does not have local html files or js codes
#Time: 31022
`

**Comment by SunghoLee** [comment]
Hi, thank you for your interest in HybriDroid. 

It is not a problem, because the NormalAliasFlowTest app is not a hybrid app. If you want to test HybriDroid, you should use the apps in kr.ac.kaist.wala.hybridroid.test.data directory.

If you have any questions, please let me know about that.
Thank you :)

**Comment by jennifersuggar** [comment]
Thank you！ as I follow your guid，it encounter below：
`root@czf:/home/czf/HybriDroid-master# java -jar hybridroid.jar -cfg -t kr.ac.kaist.wala.hybridroid.test.data/ConstantValueTest.apk -p wala.properties
#lib: /home/czf/HybriDroid-master/data/android.jar(true)
I: Using Apktool 2.0.2 on ConstantValueTest.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
===== App Data =====

  version: 2.0.2
  apkFileName: ConstantValueTest.apk
  isFrameworkApk: false
  usesFramework: 
    ids: -1
  sdkInfo: 
    minSdkVersion: '8'
    targetSdkVersion: '21'
  packageInfo: 
    forced-package-id: '127'
  versionInfo: 
    versionCode: '1'
    versionName: '1.0'
  sharedLibrary: false
  doNotCompress: -resources.arsc
====================
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Field Def analysis...
Build Constraint Graph...
Optimize Constraint Graph...
Solving the constraints...
#StringAnalysisEndTime: 24639
===== Not Found Error =====
===========================
#Time: 55742
`
 Failed to load class "org.slf4j.impl.StaticLoggerBinder"and where can I find event log？

**Comment by SunghoLee** [comment]
Hi. SLF4J is a library for logging system used in WALA. Because the failure does not affect the analysis process, it does not matter. 

And what event log do you want to check?

**Comment by jennifersuggar** [comment]
about privacy leakage log.

**Comment by SunghoLee** [comment]
When HybriDroid finds some private information leakage flows, it prints messages on your terminal.
But, I think that you did not execute the taint analysis module of HybriDroid. You can track private information leakage using PrivateLeakageDetector module as follow:

```
PrivateLeakageDetector pld = new PrivateLeakageDetector(callGraph, pointerAnalysis);

// add your sources				pld.addSource(MethodReference.findOrCreate(TypeReference.find(ClassLoaderReference.Application, "Landroid/telephony/TelephonyManager"), Selector.make("getLine1Number()Ljava/lang/String;")));
				
//add your sinks
pld.addSink(MethodReference.findOrCreate(TypeReference.find(JavaScriptTypes.jsLoader, "Lpreamble.js/XMLHttpRequest/xhr_send"), Selector.make("do()LRoot")));

//run the taint anlayzer
pld.analyze();

//print found flows				
for(PrivateLeakageDetector.LeakWarning w : pld.getWarnings()){
   System.out.println("=========");
   System.out.println(w);
   System.out.println("=========");

   //print found flows as a graph
   w.printPathFlow("leak.dot");
}
```
