### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by zsm116** [SunghoLee/HybriDroid#7]
Hello, I'm interested in this project.
When I build the project, I meet some errors .
I'd be appreciate if you can give me some advice!

zsm@zsm-virtual-machine:~/HybriDroid$ make

> Task :kr.ac.kaist.wala.hybridroid.util:compileJava FAILED
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:9: error: package com.ibm.wala.dalvik.classLoader does not exist
import com.ibm.wala.dalvik.classLoader.DexIRFactory;
                                      ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:10: error: package com.ibm.wala.ipa.callgraph does not exist
import com.ibm.wala.ipa.callgraph.CGNode;
                                 ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:11: error: package com.ibm.wala.ipa.callgraph does not exist
import com.ibm.wala.ipa.callgraph.CallGraph;
                                 ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:12: error: package com.ibm.wala.ipa.callgraph.impl does not exist
import com.ibm.wala.ipa.callgraph.impl.Everywhere;
                                      ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:13: error: package com.ibm.wala.ssa does not exist
import com.ibm.wala.ssa.IR;
                       ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:14: error: package com.ibm.wala.ssa does not exist
import com.ibm.wala.ssa.SSAInstruction;
                       ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:15: error: package com.ibm.wala.ssa does not exist
import com.ibm.wala.ssa.SSAOptions;
                       ^
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:22: error: cannot find symbol
    public static void printIR(CallGraph cg, String out, Filter f){
                               ^
  symbol:   class CallGraph
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:62: error: cannot find symbol
    private static IR makeIR(CGNode n){
                             ^
  symbol:   class CGNode
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:62: error: cannot find symbol
    private static IR makeIR(CGNode n){
                   ^
  symbol:   class IR
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:77: error: cannot find symbol
        boolean filter(CGNode n);
                       ^
  symbol:   class CGNode
  location: interface Filter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:29: error: cannot find symbol
            for(CGNode n : cg) {
                ^
  symbol:   class CGNode
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:34: error: cannot find symbol
                IR ir = makeIR(n);
                ^
  symbol:   class IR
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:36: error: cannot find symbol
                    SSAInstruction[] insts = ir.getInstructions();
                    ^
  symbol:   class SSAInstruction
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:39: error: cannot find symbol
                        SSAInstruction inst = insts[i];
                        ^
  symbol:   class SSAInstruction
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:45: error: cannot find symbol
                    Iterator<CGNode> iSucc = cg.getSuccNodes(n);
                             ^
  symbol:   class CGNode
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:47: error: cannot find symbol
                        CGNode succ = iSucc.next();
                        ^
  symbol:   class CGNode
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:63: error: cannot find symbol
        IR ir = n.getIR();
        ^
  symbol:   class IR
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:66: error: cannot find symbol
            DexIRFactory irFactory = new DexIRFactory();
            ^
  symbol:   class DexIRFactory
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:66: error: cannot find symbol
            DexIRFactory irFactory = new DexIRFactory();
                                         ^
  symbol:   class DexIRFactory
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:68: error: cannot find symbol
                ir = irFactory.makeIR(n.getMethod(), Everywhere.EVERYWHERE, SSAOptions.defaultOptions());
                                                     ^
  symbol:   variable Everywhere
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:68: error: cannot find symbol
                ir = irFactory.makeIR(n.getMethod(), Everywhere.EVERYWHERE, SSAOptions.defaultOptions());
                                                                            ^
  symbol:   variable SSAOptions
  location: class IRPrinter
/home/zsm/HybriDroid/kr.ac.kaist.wala.hybridroid.util/src/kr/ac/kaist/wala/hybridroid/util/print/IRPrinter.java:83: error: cannot find symbol
                        public boolean filter(CGNode n) {
                                              ^
  symbol: class CGNode
23 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kr.ac.kaist.wala.hybridroid.util:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
Makefile:30: recipe for target 'kr.ac.kaist.wala.hybridroid/build/libs/kr.ac.kaist.wala.hybridroid.jar' failed
make: *** [kr.ac.kaist.wala.hybridroid/build/libs/kr.ac.kaist.wala.hybridroid.jar] Error 1

**Comment by SunghoLee** [comment]
Hi. Thanks for your interest in our project!
I got the same result as what you got. It's because of the changed structures of WALA latest version. We will fix it as soon as possible.
Please be patient with it.
Thank you.

**Comment by SunghoLee** [comment]
Hi, there! We finally have fixed the issue :) 
Please check the newest version of HybriDroid!
Thank you :)

**Comment by zsm116** [comment]
I can build the newest version of HybriDroid successfully.
Thank you very much.
